version: '3'
services:

  app:
    build: .
    container_name: flask_app
    restart: unless-stopped
    command: flask run
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    network_mode: host

  mysql:
    container_name: flask_mysql
    image: mysql:5.7
    volumes:
      - ./DB:/var/lib/mysql
    env_file:
      - ./.env
    network_mode: host
    restart: always
